export { default as MoneyOffIcon } from '@mui/icons-material/MoneyOff';
export { default as RedeemIcon } from '@mui/icons-material/Redeem';
export { default as InventoryIcon } from '@mui/icons-material/Inventory';
export { default as StorageIcon } from '@mui/icons-material/Storage';
export { default as MemoryIcon } from '@mui/icons-material/Memory';
export { default as PointOfSaleIcon } from '@mui/icons-material/PointOfSale';
export { default as LeaderboardIcon } from '@mui/icons-material/Leaderboard';
export { default as SchemaIcon } from '@mui/icons-material/Schema';
export { default as DesktopAccessDisabledIcon } from '@mui/icons-material/DesktopAccessDisabled';
export { default as WorkspacesIcon } from '@mui/icons-material/Workspaces';
export { default as AccountBalanceIcon } from '@mui/icons-material/AccountBalance';
export { default as GroupsIcon } from '@mui/icons-material/Groups';
export { default as ShowChartIcon } from '@mui/icons-material/ShowChart';
export { default as StackedLineChartIcon } from '@mui/icons-material/StackedLineChart';
export { default as ManageSearchIcon } from '@mui/icons-material/ManageSearch';
export { default as PeopleAltIcon } from '@mui/icons-material/PeopleAlt';
export { default as InsertDriveFileIcon } from '@mui/icons-material/InsertDriveFile';
export { default as ListAltIcon } from '@mui/icons-material/ListAlt';
export { default as ArticleIcon } from '@mui/icons-material/Article';
export { default as NoteIcon } from '@mui/icons-material/Note';
export { default as ListIcon } from '@mui/icons-material/List';
export { default as BlenderIcon } from '@mui/icons-material/Blender';
export { default as AttachMoneyIcon } from '@mui/icons-material/AttachMoney';
export { default as DashboardCustomizeIcon } from '@mui/icons-material/DashboardCustomize';
export { default as PaymentIcon } from '@mui/icons-material/Payment';
export { default as AppRegistrationIcon } from '@mui/icons-material/AppRegistration';
export { default as HouseboatIcon } from '@mui/icons-material/Houseboat';
export { default as PollIcon } from '@mui/icons-material/Poll';
export { default as InfoIcon } from '@mui/icons-material/Info';
export { default as ShoppingCartIcon } from '@mui/icons-material/ShoppingCart';
export { default as TuneSharp } from '@mui/icons-material/TuneSharp';
export { default as PaidIcon } from '@mui/icons-material/Paid';
export { default as ReceiptLongIcon } from '@mui/icons-material/ReceiptLong';
export { default as DescriptionIcon } from '@mui/icons-material/Description';
export { default as PixIcon } from '@mui/icons-material/Pix';
export { default as MailIcon } from '@mui/icons-material/Mail';
export { default as LocalGasStationIcon } from '@mui/icons-material/LocalGasStation';
export { default as HistoryIcon } from '@mui/icons-material/History';
export { default as AccessibilityNewIcon } from '@mui/icons-material/AccessibilityNew';
export { default as PlaylistAddCheckIcon } from '@mui/icons-material/PlaylistAddCheck';
export { default as CurrencyRupeeIcon } from '@mui/icons-material/CurrencyRupee';
export { default as DateRangeIcon } from '@mui/icons-material/DateRange';
export { default as AssignmentReturnedIcon } from '@mui/icons-material/AssignmentReturned';
export { default as FormatListBulletedIcon } from '@mui/icons-material/FormatListBulleted';
export { default as PlaylistAddCircleIcon } from '@mui/icons-material/PlaylistAddCircle';
export { default as AddCircleIcon } from '@mui/icons-material/AddCircle';
export { default as paymentIcon } from '../assets/dashboardIcons/10payment.svg';
export { default as ReportIcon } from '@mui/icons-material/Report';
export { default as duedateIcon } from '../assets/dashboardIcons/due-date.svg';
export { default as dashboardIcon } from '../assets/dashboardIcons/dashboard.svg';
export { default as contactIcon } from '../assets/dashboardIcons/contact_icon.png';
export { default as posIcon } from '../assets/dashboardIcons/pos.svg';
export { default as posreportIcon } from '../assets/dashboardIcons/reports.svg';
export { default as salesmanIcon } from '../assets/dashboardIcons/salesman.svg';
export { default as checkmappingIcon } from '../assets/dashboardIcons/checklist.svg';
export { default as visitsIcon } from '../assets/dashboardIcons/visitor.svg';
export { default as trackingIcon } from '../assets/dashboardIcons/tracking.svg';
export { default as ReceivablesIcon } from '../assets/dashboardIcons/receive-money.svg';
export { default as pricelistIcon } from '../assets/dashboardIcons/price-list.svg';
export { default as purchaseIcon } from '../assets/dashboardIcons/purchase.svg';
export { default as purchaseorderIcon } from '../assets/dashboardIcons/purchase-order.svg';
export { default as payableIcon } from '../assets/dashboardIcons/payable.svg';
export { default as productIcon } from '../assets/dashboardIcons/product-management.svg';
export { default as transferIcon } from '../assets/dashboardIcons/transfer.svg';
export { default as reconciliationIcon } from '../assets/dashboardIcons/reconciliation.svg'
export { default as payIcon } from '../assets/dashboardIcons/pay.svg';
export { default as paymentreportIcon } from '../assets/dashboardIcons/report.svg';
export { default as cashboxIcon } from '../assets/dashboardIcons/cashbox.svg';
export { default as accountsIcon } from '../assets/dashboardIcons/accounts.svg';
export { default as creditcardIcon } from '../assets/dashboardIcons/credit-card.svg';
export { default as profitIcon } from '../assets/dashboardIcons/profit.svg';
export { default as balanceIcon } from '../assets/dashboardIcons/balance.svg';
export { default as bankstatementIcon } from '../assets/dashboardIcons/bank-statement.svg';
export { default as schemeIcon } from '../assets/dashboardIcons/scheme.svg';
export { default as settingsIcon } from '../assets/dashboardIcons/settings.svg';
export { default as bankingIcon } from '../assets/dashboardIcons/banking.svg';
export { default as messagesIcon } from '../assets/dashboardIcons/messages.svg';
export { default as themeIcon } from '../assets/dashboardIcons/theme.svg';
export { default as requestIcon } from '../assets/dashboardIcons/request.svg';
export { default as shiftIcon } from '../assets/dashboardIcons/shift.svg';
export { default as salaryIcon } from '../assets/dashboardIcons/salary.svg';
export { default as closeIcon } from '../assets/dashboardIcons/close.svg';
export { default as expenseIcon } from '../assets/dashboardIcons/07salary.svg';
export { default as sellerIcon } from '../assets/dashboardIcons/seller.svg';
export { default as ContactsIcon } from '@mui/icons-material/Contacts';
export { default as SellIcon } from '@mui/icons-material/Sell';
export { default as SavingsIcon } from '@mui/icons-material/Savings';
export { default as PinDropIcon } from '@mui/icons-material/PinDrop';
export { default as RequestQuoteIcon } from '@mui/icons-material/RequestQuote';
export { default as ErrorIcon } from '@mui/icons-material/Error';
export { default as ErrorOutlineIcon } from '@mui/icons-material/ErrorOutline';
export { default as MyLocationIcon } from '@mui/icons-material/MyLocation';
export { default as DirectionsBikeIcon } from '@mui/icons-material/DirectionsBike';
export { default as AssignmentIndIcon } from '@mui/icons-material/AssignmentInd';
export { default as AssessmentIcon } from '@mui/icons-material/Assessment';
export { default as EditRoadIcon } from '@mui/icons-material/EditRoad';
export { default as TaskIcon } from '@mui/icons-material/Task';
export { default as FeedIcon } from '@mui/icons-material/Feed';
export { default as BrandingWatermarkIcon } from '@mui/icons-material/BrandingWatermark';
export { default as QuestionAnswerIcon } from '@mui/icons-material/QuestionAnswer';
export { default as MonetizationOnIcon } from '@mui/icons-material/MonetizationOn';
export { default as CameraFrontSharpIcon } from '@mui/icons-material/CameraFrontSharp';
export { default as CameraFrontIcon } from '@mui/icons-material/CameraFront';
export { default as QueuePlayNextIcon } from '@mui/icons-material/QueuePlayNext';
export { default as LocalOfferIcon } from '@mui/icons-material/LocalOffer';
export { default as CampaignIcon } from '@mui/icons-material/Campaign';
export { default as FlakyIcon } from '@mui/icons-material/Flaky';
export { default as FollowTheSignsIcon } from '@mui/icons-material/FollowTheSigns';
export { default as ApprovalIcon } from '@mui/icons-material/HowToReg';
export { default as LocationCityIcon } from '@mui/icons-material/LocationCity';
export { default as PolicyIcon } from '@mui/icons-material/Policy';
export { default as QrCodeScannerIcon } from '@mui/icons-material/QrCodeScanner';
export { default as WorkHistoryIcon } from '@mui/icons-material/WorkHistory';
export { default as OverTimeReportIcon } from '@mui/icons-material/PendingActions';
export { default as AddAlertIcon } from '@mui/icons-material/AddAlert';
export { default as AssuredWorkloadIcon } from '@mui/icons-material/AssuredWorkload';
export { default as FindInPageIcon } from '@mui/icons-material/FindInPage';
export { default as PermMediaIcon } from '@mui/icons-material/PermMedia';
export {default as FactCheckIcon} from '@mui/icons-material/FactCheck';
import { MdOutlineDns } from 'react-icons/md';
export {default as LayersIcon} from '@mui/icons-material/Layers';
export { default as employeeDocumentsIcon } from '../assets/dashboardIcons/employee-documents.png';
export { default as companyInfoIcon } from '../assets/dashboardIcons/company-info.png';
export { default as reportIcon } from '../assets/dashboardIcons/reports.png';
export { default as workDurationIcon } from '../assets/dashboardIcons/workDuration-report.png';
export { default as leaveReportIcon } from '../assets/dashboardIcons/leave-report.png';
export { default as salaryReportIcon } from '../assets/dashboardIcons/salary-report.png';
export { default as relievedEmployeeIcon } from '../assets/dashboardIcons/relieved-employee.png';
export { default as scheduleShiftIcon } from '../assets/dashboardIcons/schedule-shift.png';
export { default as createShiftIcon } from '../assets/dashboardIcons/create-shift.png';
export { default as viewShiftIcon } from '../assets/dashboardIcons/view-shifts.png';
export { default as attendanceReportIcon } from '../assets/dashboardIcons/attendance-report.png';
export { default as assignSalaryIcon } from '../assets/dashboardIcons/assign-salary.png';
export { default as salaryStructureIcon } from '../assets/dashboardIcons/salary-structure.png';
export { default as NewsalaryIcon} from '../assets/dashboardIcons/salaryicon.png';
export { default as salaryReportBankIcon} from '../assets/dashboardIcons/salaryReportForBank.png';
export { default as salaryProcessIcon} from '../assets/dashboardIcons/salary-process.png';
export { default as requestReportIcon} from '../assets/dashboardIcons/request-report.png';
export { default as SettingsSuggestIcon } from '@mui/icons-material/SettingsSuggest';
export {default as CurrencyExchangeIcon} from '@mui/icons-material/CurrencyExchange';
export {default as RejectedRequestIcon} from '../assets/dashboardIcons/rejected.png';
export {default as claims} from '../assets/dashboardIcons/Claims.png';
export {default as EventIcon} from '@mui/icons-material/Event';
export {default as SubscriptionIcon} from '../assets/dashboardIcons/subscription.png';
export { default as RequestPageIcon } from '@mui/icons-material/RequestPage';
export {default as HelpCenter} from '@mui/icons-material/HelpCenter';
export {default as LateAndEarlyIcon} from '../assets/dashboardIcons/lateAndEarly.png'
export {default as ManualAttendanceIcon} from '../assets/dashboardIcons/manual-attendance.png';
export {default as FaceAttendance} from '../assets/dashboardIcons/face.png';
export {default as FaceRegistration} from '../assets/dashboardIcons/FaceRegistration.png';
export {default as FlakyRoundedIcon} from '@mui/icons-material/FlakyRounded';
export {default as MobiledataOffIcon} from '@mui/icons-material/MobiledataOff';
export {default as SummarizeIcon} from '@mui/icons-material/Summarize';
export {default as SuperAdminIcon} from '@mui/icons-material/AdminPanelSettings';
export {default as SettingsIcon} from '@mui/icons-material/Settings';
export {default as DashboardOutlined} from '@mui/icons-material/DashboardOutlined';
export {default as BarChartOutlined} from '@mui/icons-material/BarChartOutlined';
export {default as BusinessOutlined} from '@mui/icons-material/BusinessOutlined';
export {default as HourglassEmptyOutlined} from '@mui/icons-material/HourglassEmptyOutlined';
export {default as ThumbDownOutlined} from '@mui/icons-material/ThumbDownOutlined';
export {default as WhatsApp} from '@mui/icons-material/WhatsApp';
export {default as OfflineAttendance} from '@mui/icons-material/WifiOff';
export {default as RocketLaunchIcon} from '@mui/icons-material/RocketLaunch';

export {default as CalendarMonthIcon} from '../assets/dashboardIcons/calendarIcon.png';
export {default as LeadsApprovalIcon} from '../assets/dashboardIcons/calendarIcon.png';
export {default as SupervisedUserCircleIcon} from '@mui/icons-material/SupervisedUserCircle';
export {default as HealthAndSafetyIcon} from '@mui/icons-material/HealthAndSafety';
export {default as GppGoodIcon} from '@mui/icons-material/GppGood';
export {default as ManageHistoryIcon} from '@mui/icons-material/ManageHistory';
export {default as AccountBalanceWallet} from '@mui/icons-material/AccountBalanceWallet';
export {default as AssetsIcon} from '../assets/icon/Assets.svg';
export {default as RenewalsIcon} from '../assets/icon/renewals.svg';
export {default as ServiceDueIcon} from '../assets/icon/ServiceDue.svg';
export {default as AuditsIcon} from '../assets/icon/Audits.svg';
export {default as AuditRequestIcon} from '../assets/icon/AuditRequest.svg';
export {default as ConfigurationIcon} from '../assets/icon/Configuration.svg';
export {default as ContactIcon} from '../assets/icon/Contacts.svg';
export {default as ChatsIcon} from '../assets/icon/Chat.svg';
export {default as Compliances} from '../assets/icon/compliances.svg';
export {default as IncentiveIcon} from '../assets/dashboardIcons/incentive.png'
export {default as AverageCreditDaysIcon} from '../../src/assets/dashboardIcons/AverageCreditDays.svg'
export {default as TotalReceivableIcon} from '../../src/assets/dashboardIcons/Total Receivable.svg'
export {default as DaysExceedsIcon} from '../../src/assets/dashboardIcons/DaysExceeds.svg'
export {default as DaysReceivableIcon} from '../../src/assets/dashboardIcons/DaysReceivable.svg'
export {default as InvoiceIcon} from '@mui/icons-material/Description';
export {default as AccounntsIcon} from '../../src/assets/dashboardIcons/NewAccounts.svg';
export {default as SalesmanIcon} from '../../src/assets/dashboardIcons/NewSalesMan.svg';
export {default as CashAndBank} from '../../src/assets/dashboardIcons/Cash and Bank.svg';
export {default as NewInventoryIcon} from '../../src/assets/dashboardIcons/Inventory.svg';
export {default as PurchaseIcon} from '../../src/assets/dashboardIcons/Newpurchase.svg';
export {default as NewApprovalIcon} from '../../src/assets/dashboardIcons/Approval.svg';
export {default as NewReportIcon} from '../../src/assets/dashboardIcons/NewReports.svg';
export {default as PlanIcon} from '../../src/assets/dashboardIcons/plan.png';
export {default as MemberIcon} from '../../src/assets/dashboardIcons/member.png';
export {default as NewPaymentIcon} from '../../src/assets/dashboardIcons/newPaymentIcon.svg';
export {default as CustomerInvoiceIcon} from '../../src/assets/dashboardIcons/customerInvoice.png';
export {default as CustomerDeliveryChallanIcon} from '../../src/assets/dashboardIcons/customerDeliveryChallan.png';
export {default as CustomerCreditNoteIcon} from '../../src/assets/dashboardIcons/customerCreditNote.png';
export {default as CustomerQuotationIcon} from '../../src/assets/dashboardIcons/customerQuotation.png';
export {default as CustomerReceiptsIcon} from '../../src/assets/dashboardIcons/customerReceipts.png';
export {default as CustomerGeneralInfoIcon} from '../../src/assets/dashboardIcons/customerGeneralInfo.png';
export {default as CustomerOthersIcon} from '../../src/assets/dashboardIcons/customerOthers.png';
export {default as CustomerStatementsIcon} from '../../src/assets/dashboardIcons/customerStatements.png';
export {default as CustomersalesOrderIcon} from '../../src/assets/dashboardIcons/customerSalesOrder.png';
export {default as DefectIcon} from '../../src/assets/dashboardIcons/defects__2 2.svg'
export {default as DescriptionOutlined} from '@mui/icons-material/DescriptionOutlined';

// ── Finance & Accounting ──
export {default as AccountBalanceWalletIcon} from '@mui/icons-material/AccountBalanceWallet';
export {default as ReceiptIcon} from '@mui/icons-material/Receipt';
export {default as CreditCardIcon} from '@mui/icons-material/CreditCard';
export {default as CreditScoreIcon} from '@mui/icons-material/CreditScore';
export {default as PriceCheckIcon} from '@mui/icons-material/PriceCheck';
export {default as CalculateIcon} from '@mui/icons-material/Calculate';
export {default as AccountTreeIcon} from '@mui/icons-material/AccountTree';
export {default as SwapHorizIcon} from '@mui/icons-material/SwapHoriz';
export {default as CompareArrowsIcon} from '@mui/icons-material/CompareArrows';
export {default as TrendingUpIcon} from '@mui/icons-material/TrendingUp';
export {default as TrendingDownIcon} from '@mui/icons-material/TrendingDown';
export {default as WalletIcon} from '@mui/icons-material/Wallet';
export {default as CurrencyBitcoinIcon} from '@mui/icons-material/CurrencyBitcoin';
export {default as PriceChangeIcon} from '@mui/icons-material/PriceChange';

// ── Sales & CRM ──
export {default as StorefrontIcon} from '@mui/icons-material/Storefront';
export {default as ShoppingBagIcon} from '@mui/icons-material/ShoppingBag';
export {default as ShoppingBasketIcon} from '@mui/icons-material/ShoppingBasket';
export {default as AddShoppingCartIcon} from '@mui/icons-material/AddShoppingCart';
export {default as LoyaltyIcon} from '@mui/icons-material/Loyalty';
export {default as HandshakeIcon} from '@mui/icons-material/Handshake';
export {default as SupportAgentIcon} from '@mui/icons-material/SupportAgent';
export {default as ContactPhoneIcon} from '@mui/icons-material/ContactPhone';
export {default as ContactMailIcon} from '@mui/icons-material/ContactMail';
export {default as PersonSearchIcon} from '@mui/icons-material/PersonSearch';
export {default as GroupAddIcon} from '@mui/icons-material/GroupAdd';
export {default as GroupRemoveIcon} from '@mui/icons-material/GroupRemove';
export {default as ThumbUpIcon} from '@mui/icons-material/ThumbUp';
export {default as ThumbDownIcon} from '@mui/icons-material/ThumbDown';
export {default as StarIcon} from '@mui/icons-material/Star';
export {default as StarBorderIcon} from '@mui/icons-material/StarBorder';

// ── Inventory & Warehouse ──
export {default as WarehouseIcon} from '@mui/icons-material/Warehouse';
export {default as CategoryIcon} from '@mui/icons-material/Category';
export {default as WidgetsIcon} from '@mui/icons-material/Widgets';
export {default as ViewInArIcon} from '@mui/icons-material/ViewInAr';
export {default as QrCode2Icon} from '@mui/icons-material/QrCode2';
export {default as LocalShippingIcon} from '@mui/icons-material/LocalShipping';
export {default as MoveToInboxIcon} from '@mui/icons-material/MoveToInbox';
export {default as OutboxIcon} from '@mui/icons-material/Outbox';
export {default as ArchiveIcon} from '@mui/icons-material/Archive';
export {default as UnarchiveIcon} from '@mui/icons-material/Unarchive';
export {default as PackageIcon} from '@mui/icons-material/Inventory2';
export {default as ScaleIcon} from '@mui/icons-material/Scale';
export {default as StraightenIcon} from '@mui/icons-material/Straighten';

// ── HR & Payroll ──
export {default as BadgeIcon} from '@mui/icons-material/Badge';
export {default as PersonIcon} from '@mui/icons-material/Person';
export {default as PersonAddIcon} from '@mui/icons-material/PersonAdd';
export {default as PersonRemoveIcon} from '@mui/icons-material/PersonRemove';
export {default as GroupsRoundedIcon} from '@mui/icons-material/Groups';
export {default as WorkIcon} from '@mui/icons-material/Work';
export {default as WorkOutlineIcon} from '@mui/icons-material/WorkOutline';
export {default as BusinessCenterIcon} from '@mui/icons-material/BusinessCenter';
export {default as SchoolIcon} from '@mui/icons-material/School';
export {default as CakeIcon} from '@mui/icons-material/Cake';
export {default as CardGiftcardIcon} from '@mui/icons-material/CardGiftcard';
export {default as EmojiEventsIcon} from '@mui/icons-material/EmojiEvents';
export {default as MilitaryTechIcon} from '@mui/icons-material/MilitaryTech';
export {default as VolunteerActivismIcon} from '@mui/icons-material/VolunteerActivism';
export {default as AccessTimeIcon} from '@mui/icons-material/AccessTime';
export {default as TimerIcon} from '@mui/icons-material/Timer';
export {default as ScheduleIcon} from '@mui/icons-material/Schedule';
export {default as EventAvailableIcon} from '@mui/icons-material/EventAvailable';
export {default as EventBusyIcon} from '@mui/icons-material/EventBusy';
export {default as HolidayVillageIcon} from '@mui/icons-material/HolidayVillage';
export {default as FingerprintIcon} from '@mui/icons-material/Fingerprint';
export {default as HowToRegIcon} from '@mui/icons-material/HowToReg';
export {default as PersonOffIcon} from '@mui/icons-material/PersonOff';

// ── Reports & Analytics ──
export {default as AnalyticsIcon} from '@mui/icons-material/Analytics';
export {default as InsightsIcon} from '@mui/icons-material/Insights';
export {default as PieChartIcon} from '@mui/icons-material/PieChart';
export {default as DonutLargeIcon} from '@mui/icons-material/DonutLarge';
export {default as BarChartIcon} from '@mui/icons-material/BarChart';
export {default as TimelineIcon} from '@mui/icons-material/Timeline';
export {default as BubbleChartIcon} from '@mui/icons-material/BubbleChart';
export {default as TableChartIcon} from '@mui/icons-material/TableChart';
export {default as DataUsageIcon} from '@mui/icons-material/DataUsage';
export {default as TrendingFlatIcon} from '@mui/icons-material/TrendingFlat';
export {default as SpeedIcon} from '@mui/icons-material/Speed';
export {default as QueryStatsIcon} from '@mui/icons-material/QueryStats';

// ── Documents & Files ──
export {default as FolderIcon} from '@mui/icons-material/Folder';
export {default as FolderOpenIcon} from '@mui/icons-material/FolderOpen';
export {default as FolderSharedIcon} from '@mui/icons-material/FolderShared';
export {default as FileCopyIcon} from '@mui/icons-material/FileCopy';
export {default as FileDownloadIcon} from '@mui/icons-material/FileDownload';
export {default as FileUploadIcon} from '@mui/icons-material/FileUpload';
export {default as CloudUploadIcon} from '@mui/icons-material/CloudUpload';
export {default as CloudDownloadIcon} from '@mui/icons-material/CloudDownload';
export {default as AttachFileIcon} from '@mui/icons-material/AttachFile';
export {default as TextSnippetIcon} from '@mui/icons-material/TextSnippet';
export {default as TopicIcon} from '@mui/icons-material/Topic';
export {default as NoteAddIcon} from '@mui/icons-material/NoteAdd';
export {default as PostAddIcon} from '@mui/icons-material/PostAdd';
export {default as ContentPasteIcon} from '@mui/icons-material/ContentPaste';

// ── Admin & Settings ──
export {default as AdminPanelSettingsIcon} from '@mui/icons-material/AdminPanelSettings';
export {default as ManageAccountsIcon} from '@mui/icons-material/ManageAccounts';
export {default as TuneIcon} from '@mui/icons-material/Tune';
export {default as BuildIcon} from '@mui/icons-material/Build';
export {default as BuildCircleIcon} from '@mui/icons-material/BuildCircle';
export {default as SecurityIcon} from '@mui/icons-material/Security';
export {default as ShieldIcon} from '@mui/icons-material/Shield';
export {default as LockIcon} from '@mui/icons-material/Lock';
export {default as LockOpenIcon} from '@mui/icons-material/LockOpen';
export {default as VpnKeyIcon} from '@mui/icons-material/VpnKey';
export {default as ToggleOnIcon} from '@mui/icons-material/ToggleOn';
export {default as DisplaySettingsIcon} from '@mui/icons-material/DisplaySettings';
export {default as IntegrationInstructionsIcon} from '@mui/icons-material/IntegrationInstructions';
export {default as ApiIcon} from '@mui/icons-material/Api';
export {default as ExtensionIcon} from '@mui/icons-material/Extension';
export {default as PowerSettingsNewIcon} from '@mui/icons-material/PowerSettingsNew';

// ── Communication ──
export {default as EmailIcon} from '@mui/icons-material/Email';
export {default as ChatIcon} from '@mui/icons-material/Chat';
export {default as ForumIcon} from '@mui/icons-material/Forum';
export {default as CommentIcon} from '@mui/icons-material/Comment';
export {default as AnnouncementIcon} from '@mui/icons-material/Announcement';
export {default as NotificationsIcon} from '@mui/icons-material/Notifications';
export {default as NotificationsActiveIcon} from '@mui/icons-material/NotificationsActive';
export {default as SmsIcon} from '@mui/icons-material/Sms';
export {default as PhoneIcon} from '@mui/icons-material/Phone';
export {default as CallIcon} from '@mui/icons-material/Call';
export {default as SendIcon} from '@mui/icons-material/Send';
export {default as ShareIcon} from '@mui/icons-material/Share';
export {default as MarkEmailReadIcon} from '@mui/icons-material/MarkEmailRead';

// ── Project & Task Management ──
export {default as AssignmentIcon} from '@mui/icons-material/Assignment';
export {default as AssignmentTurnedInIcon} from '@mui/icons-material/AssignmentTurnedIn';
export {default as AssignmentLateIcon} from '@mui/icons-material/AssignmentLate';
export {default as ChecklistIcon} from '@mui/icons-material/Checklist';
export {default as RuleIcon} from '@mui/icons-material/Rule';
export {default as PendingActionsIcon} from '@mui/icons-material/PendingActions';
export {default as PublishedWithChangesIcon} from '@mui/icons-material/PublishedWithChanges';
export {default as FlagIcon} from '@mui/icons-material/Flag';
export {default as BookmarkIcon} from '@mui/icons-material/Bookmark';
export {default as PushPinIcon} from '@mui/icons-material/PushPin';
export {default as LabelIcon} from '@mui/icons-material/Label';
export {default as LabelImportantIcon} from '@mui/icons-material/LabelImportant';

// ── Bugs, Errors & Support ──
export {default as BugReportIcon} from '@mui/icons-material/BugReport';
export {default as ReportProblemIcon} from '@mui/icons-material/ReportProblem';
export {default as WarningIcon} from '@mui/icons-material/Warning';
export {default as WarningAmberIcon} from '@mui/icons-material/WarningAmber';
export {default as DangerousIcon} from '@mui/icons-material/Dangerous';
export {default as BlockIcon} from '@mui/icons-material/Block';
export {default as DoNotDisturbIcon} from '@mui/icons-material/DoNotDisturb';
export {default as CheckCircleIcon} from '@mui/icons-material/CheckCircle';
export {default as CancelIcon} from '@mui/icons-material/Cancel';
export {default as HelpIcon} from '@mui/icons-material/Help';
export {default as HelpOutlineIcon} from '@mui/icons-material/HelpOutline';
export {default as LiveHelpIcon} from '@mui/icons-material/LiveHelp';
export {default as FeedbackIcon} from '@mui/icons-material/Feedback';
export {default as TroubleshootIcon} from '@mui/icons-material/Troubleshoot';

// ── Location & Maps ──
export {default as PlaceIcon} from '@mui/icons-material/Place';
export {default as MapIcon} from '@mui/icons-material/Map';
export {default as NearMeIcon} from '@mui/icons-material/NearMe';
export {default as ExploreIcon} from '@mui/icons-material/Explore';
export {default as PublicIcon} from '@mui/icons-material/Public';
export {default as LanguageIcon} from '@mui/icons-material/Language';
export {default as HomeIcon} from '@mui/icons-material/Home';
export {default as BusinessIcon} from '@mui/icons-material/Business';
export {default as ApartmentIcon} from '@mui/icons-material/Apartment';
export {default as StoreIcon} from '@mui/icons-material/Store';
export {default as LocalMallIcon} from '@mui/icons-material/LocalMall';

// ── Miscellaneous ERP ──
export {default as VerifiedIcon} from '@mui/icons-material/Verified';
export {default as VerifiedUserIcon} from '@mui/icons-material/VerifiedUser';
export {default as GavelIcon} from '@mui/icons-material/Gavel';
export {default as BalanceIcon} from '@mui/icons-material/Balance';
export {default as AutorenewIcon} from '@mui/icons-material/Autorenew';
export {default as SyncIcon} from '@mui/icons-material/Sync';
export {default as UpdateIcon} from '@mui/icons-material/Update';
export {default as HistoryToggleOffIcon} from '@mui/icons-material/HistoryToggleOff';
export {default as RestoreIcon} from '@mui/icons-material/Restore';
export {default as DeleteIcon} from '@mui/icons-material/Delete';
export {default as DeleteForeverIcon} from '@mui/icons-material/DeleteForever';
export {default as PrintIcon} from '@mui/icons-material/Print';
export {default as SaveIcon} from '@mui/icons-material/Save';
export {default as EditIcon} from '@mui/icons-material/Edit';
export {default as AddIcon} from '@mui/icons-material/Add';
export {default as RemoveIcon} from '@mui/icons-material/Remove';
export {default as SearchIcon} from '@mui/icons-material/Search';
export {default as FilterListIcon} from '@mui/icons-material/FilterList';
export {default as SortIcon} from '@mui/icons-material/Sort';
export {default as ViewListIcon} from '@mui/icons-material/ViewList';
export {default as ViewModuleIcon} from '@mui/icons-material/ViewModule';
export {default as GridViewIcon} from '@mui/icons-material/GridView';
export {default as DashboardIcon} from '@mui/icons-material/Dashboard';
export {default as AppsIcon} from '@mui/icons-material/Apps';
export {default as MenuBookIcon} from '@mui/icons-material/MenuBook';
export {default as AutoStoriesIcon} from '@mui/icons-material/AutoStories';
export {default as PhotoCameraIcon} from '@mui/icons-material/PhotoCamera';
export {default as ImageIcon} from '@mui/icons-material/Image';
export {default as LinkIcon} from '@mui/icons-material/Link';
export {default as QrCodeIcon} from '@mui/icons-material/QrCode';
export {default as LocalAtmIcon} from '@mui/icons-material/LocalAtm';
export {default as TokenIcon} from '@mui/icons-material/Token';
export {default as DataObjectIcon} from '@mui/icons-material/DataObject';
export {default as HubIcon} from '@mui/icons-material/Hub';
export {default as DevicesIcon} from '@mui/icons-material/Devices';
export {default as SmartphoneIcon} from '@mui/icons-material/Smartphone';
export {default as TabletIcon} from '@mui/icons-material/Tablet';
export {default as DesktopWindowsIcon} from '@mui/icons-material/DesktopWindows';
export {default as CloudIcon} from '@mui/icons-material/Cloud';
export {default as CloudDoneIcon} from '@mui/icons-material/CloudDone';
export {default as BackupIcon} from '@mui/icons-material/Backup';
export {default as DownloadIcon} from '@mui/icons-material/Download';
export {default as UploadIcon} from '@mui/icons-material/Upload';
export {default as ImportExportIcon} from '@mui/icons-material/ImportExport';
export {default as SwapVertIcon} from '@mui/icons-material/SwapVert';
export {default as CompareIcon} from '@mui/icons-material/Compare';
export {default as DifferenceIcon} from '@mui/icons-material/Difference';
export {default as MergeIcon} from '@mui/icons-material/Merge';
export {default as CallSplitIcon} from '@mui/icons-material/CallSplit';
export {default as AltRouteIcon} from '@mui/icons-material/AltRoute';
export {default as RouteIcon} from '@mui/icons-material/Route';
export {default as DirectionsIcon} from '@mui/icons-material/Directions';
export {default as LocalParkingIcon} from '@mui/icons-material/LocalParking';
export {default as ConstructionIcon} from '@mui/icons-material/Construction';
export {default as EngineeringIcon} from '@mui/icons-material/Engineering';
export {default as PrecisionManufacturingIcon} from '@mui/icons-material/PrecisionManufacturing';
export {default as FactoryIcon} from '@mui/icons-material/Factory';
export {default as AgricultureIcon} from '@mui/icons-material/Agriculture';
export {default as ScienceIcon} from '@mui/icons-material/Science';
export {default as BiotechIcon} from '@mui/icons-material/Biotech';
export {default as MedicalServicesIcon} from '@mui/icons-material/MedicalServices';
export {default as LocalPharmacyIcon} from '@mui/icons-material/LocalPharmacy';
export {default as VaccinesIcon} from '@mui/icons-material/Vaccines';
export {default as MonitorHeartIcon} from '@mui/icons-material/MonitorHeart';
export {default as RecyclingIcon} from '@mui/icons-material/Recycling';
export {default as Inventory2Icon} from '@mui/icons-material/Inventory2';
export {default as AllInboxIcon} from '@mui/icons-material/AllInbox';
export {default as MarkunreadMailboxIcon} from '@mui/icons-material/MarkunreadMailbox';
export {default as LocalPostOfficeIcon} from '@mui/icons-material/LocalPostOffice';
export {default as DocumentScannerIcon} from '@mui/icons-material/DocumentScanner';
export {default as ScannerIcon} from '@mui/icons-material/Scanner';
export {default as ReceiptLongOutlinedIcon} from '@mui/icons-material/ReceiptLongOutlined';

export default MdOutlineDns;