import React from "react";
import { Grid, Typography, Box } from "@mui/material";
import QRCode from "react-qr-code"; // Install QR Code package if not already
import './styles.css';
import { useSelector } from 'react-redux';
import moment from "moment";

  const EWayBill = ({ E_invoice_sign,  consignee, invoice, items, appConfigData  }) => {

    const {
      appConfigReducer: { app_config_data },
    } = useSelector((state) => state);
 


let E_invoice = E_invoice_sign[0]
const { companyName, companyAddress, companyEmail, gstin, companyMobile, state } =
appConfigData || {};

const totalCost = () => {
  let total = 0;
  items?.forEach((d) => {
    const prc = d.item_unit_price
    total += (d.quantity || 1) * prc;
  });
  return total;
};

const getIgst = (data) => {
  let tax = '';
  if (data.taxes) {
    data.taxes.forEach((t) => {
      if (t.tax_group === 'IGST') {
        tax = t.tax_rate;
      }
    });
  }
  return tax;
};
const taxes = () => {
  let total = 0;
  for (let data of items) {
    const prc =
       data.item_unit_price
    const qty = data.quantity || 1;
    const tax = getIgst(data);
    total += ((prc * qty) / 100) * tax;
  }
  return total ? total : 0;
};
const getTcs = (data) => {
  let tax = '';
  if (data.taxes) {
    data.taxes.forEach((t) => {
      if (t.tax_group === 'TCS') {
        tax = t.tax_rate;
      }
    });
  }
  return tax;
};
// const tcstaxes = () => {
//   let total = 0;
//   if (tcstaxvisible === false) {
//     return total;
//   } else {
//     for (let data of items) {
//       const prc = data.item_unit_price 
//       const qty = data.quantity || 1;
//       const tax = getTcs(data);
//       total += ((prc * qty) / 100) * tax;
//     }
//     return total ? total : 0;
//   }
// };
const transmode = (value) => {
  const modes = {
      1: "1-Road",
      2: "2-Rail",
      3: "3-Air",
      4: "4-Ship",
  };
  return modes[value] || "Invalid mode"; // Return the corresponding mode or a default message
};

const getGst = () => {
  console.log('appconfigdataa', app_config_data, consignee?.state)
  const getState =
    app_config_data?.find((d) => d.key_name === 'address.state') || {};
    console.log('consignee?.state === getState.value', consignee?.state, getState.value, consignee?.state?.toLowerCase() === getState.value?.toLowerCase())
  if (consignee?.state?.toLowerCase() === getState.value?.toLowerCase()) {
    return true;
  }
  return false;
};

  return (
    <>
      <div className='tab_screen' style={{ padding: "10px", width: "100%", display: "flex", justifyContent: "center", alignItems: "center", flexDirection: "column", lineHeight:1,fontSize:'15px',fontFamily: 'Poppins, sans-serif'}}>
       <br/><br/><br/>
      <div className='tab_screen' style={{ padding: "10px", border: "1px solid black" }}>
        {/* Header Section */}
        <div style={{ textAlign: "center", marginBottom: "20px" }}>
          <Typography variant="h5" className='mlr p' style={{ fontWeight: "bold" }}>E-Way Bill</Typography>
        </div>

        <Grid container spacing={2}>
          <Grid size={10}>
            <Typography variant="body2" className='waybill'><strong>Doc No:</strong> Tax Invoice - {invoice}</Typography>
            <Typography variant="body2" className='waybill'><strong>Date:</strong> {new Date(E_invoice?.invoice[0]?.AckDt).toLocaleDateString()}</Typography>
            <br/>
            <Typography variant="body2" className='waybill'><strong>IRN:</strong> {E_invoice.invoice[0]?.Irn}</Typography>
            <Typography variant="body2" className='waybill'><strong>Ack No.:</strong> {E_invoice.invoice[0]?.AckNo}</Typography>
            <Typography variant="body2" className='waybill'>
          <strong>Ack Date:</strong> {moment(E_invoice.invoice[0]?.AckDt).format('DD/MM/YYYY')}
        </Typography>
          </Grid>
          <Grid style={{ textAlign: "center" }} size={2}>
            <Typography variant="caption"><strong>e-Invoice</strong></Typography>
            <QRCode value={E_invoice.invoice[0]?.SignedQRCode} size={80} />
          </Grid>
        </Grid>
        <hr/>
          <Typography variant="body2" className='waybill'  style={{ fontWeight: "bold" }}>1.e-Way Bill Details</Typography>
        <Grid container spacing={1}  direction='row'>
            <Grid
              size={{
                lg: 3,
                md: 4,
                sm: 6,
                xs: 12
              }}>
             <Typography variant="body2"  className='waybill'>e-Way Bill No : {E_invoice?.invoice[0]?.EwbNo}</Typography>
             <Typography variant="body2" className='waybill'>Generated by : {gstin}</Typography>
             <Typography variant="body2" className='waybill'>Supply Type : Outward-Supply</Typography>
            </Grid>
            <Grid
              size={{
                lg: 3,
                md: 4,
                sm: 6,
                xs: 12
              }}>
             <Typography variant="body2" className='waybill'>Mode : {transmode(E_invoice?.transport?.trans_mode)}</Typography>
             <Typography variant="body2" className='waybill'>Approx Distance : {E_invoice?.transport?.distance}</Typography>
             <Typography variant="body2" className='waybill'>Transcation Type : Regular</Typography>
            </Grid>
            <Grid
              size={{
                lg: 6,
                md: 4,
                sm: 6,
                xs: 12
              }}>
             <Typography variant="body2" className='waybill'>Generated Date : {E_invoice?.invoice[0]?.EwbDt}</Typography>
             <Typography variant="body2" className='waybill'>Valid Upto : {E_invoice?.invoice[0]?.EwbValidTill}</Typography>
            </Grid>
        </Grid>
       <hr/>
        {/* Supplier and Consignee Details */}
        <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>2.Address Details</Typography>
        <Grid container spacing={2}  direction='row'>
            <Grid
              size={{
                lg: 6,
                md: 4,
                sm: 6,
                xs: 12
              }}>
            <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>From:</Typography>
             <Typography variant="body2" className='waybill'>{companyName}</Typography>
             <Typography variant="body2" className='waybill'>{`GSTIN: ${gstin}`}</Typography>
             <Typography variant="body2" className='waybill'>{companyAddress}</Typography>
             <Typography variant="body2" className='waybill'>{state}</Typography><br/>
             <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>Dispatch From:</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.dispatch?.legal_name}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.dispatch?.address}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.dispatch?.location}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.dispatch?.state}</Typography>
            </Grid>
          
            <Grid
              size={{
                lg: 6,
                md: 4,
                sm: 6,
                xs: 12
              }}>
            <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>To:</Typography>
             <Typography variant="body2" className='waybill'>{consignee?.company_name}</Typography>
             <Typography variant="body2" className='waybill'>{`GSTIN: ${consignee?.tax_id}`}</Typography>
             <Typography variant="body2" className='waybill'>{`${consignee.address ? consignee.address + ',' : ''
                            } ${consignee.area ? consignee.area + ',' : ''} ${consignee.city || ''
                            }`}</Typography>
             <Typography variant="body2" className='waybill'>{consignee?.state}</Typography><br/>
             <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>Ship To:</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.shipping?.legal_name}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.shipping?.address}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.shipping?.location}</Typography>
             <Typography variant="body2" className='waybill'>{E_invoice.shipping?.state}</Typography>

            </Grid>
        </Grid>
        <hr/>
        {/* Goods Table */}
  <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>3. Goods Details</Typography>
  <table style={{ width: "100%", borderCollapse: "collapse", margin: "20px 0" }}>
    <thead>
      <tr style={{ backgroundColor: "#f2f2f2" }}>
        <th  className='waybill' style={{ border: "1px solid black", padding: "8px" }}>HSN Code</th>
        <th  className='waybill' style={{ border: "1px solid black", padding: "8px" }}>Product Name & Desc</th>
        <th  className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "center" }}>Quantity</th>
        <th className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "right" }}>Taxable Amt</th>
        <th className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "center" }}> Tax Rate:{getGst() ? '(C+S)' : 'I'}</th>
      </tr>
    </thead>
    <tbody>
      {items?.map((item, index) => (
        <tr key={index}>
          <td className='waybill' style={{ border: "1px solid black", padding: "8px" }}>{item.hsn_code}</td>
          <td className='waybill' style={{ border: "1px solid black", padding: "8px" }}>{item.name}</td>
          <td className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "center" }}>{item.quantity}</td>
          <td className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "right" }}>{item?.item_unit_price.toFixed(2)}</td>
           <td className='waybill' style={{ border: "1px solid black", padding: "8px", textAlign: "center" }}>
          {/* {getGst() ?`${(item?.taxes[0]?.tax_category?.match(/\d+/))} + ${(item?.taxes[0]?.tax_category?.match(/\d+/))}` : (item?.taxes[0]?.tax_category?.match(/\d+/))}  */}
              {item?.taxes[0]?.tax_category?.match(/\d+/)
          ? getGst()
            ? `${parseInt(item?.taxes[0]?.tax_category?.match(/\d+/)[0], 10) / 2} + ${parseInt(item?.taxes[0]?.tax_category?.match(/\d+/)[0], 10) / 2}`
            : `${parseInt(item?.taxes[0]?.tax_category?.match(/\d+/)[0], 10)}`
          : 'N/A'}
          </td>
        </tr>
      ))}
    </tbody>
  </table>

  <hr/>

  <Grid container >
    <Grid size={4}>
      <Typography variant="body2" className='waybill'><strong>Tot.Taxable Amt:</strong> {` ${(totalCost()).toFixed(2)}`}</Typography>
      {getGst() ? 
      <Typography variant="body2" className='waybill'><strong>CGST Amt :</strong> {` ${(taxes()/2).toFixed(2)}`}</Typography> :   <Typography variant="body2" className='waybill'><strong>IGST Amt :</strong> {` ${(taxes()).toFixed(2)}`}</Typography>
      }
    </Grid>
    <Grid size={4}>
    <Typography variant="body2" className='waybill'><strong>Other Amt:</strong> {}</Typography>
    {getGst() &&
    <Typography variant="body2" className='waybill'><strong>SGST Amt:</strong> {` ${(taxes()/2).toFixed(2)}`}</Typography> }
    </Grid>
    <Grid size={4}>
    <Typography variant="body2" className='waybill' align="right"><strong>Total Inv Amt:</strong> {` ${(totalCost() + taxes()).toFixed(2)}`}</Typography>
    </Grid>
    
  </Grid>
  {/* Footer Section */}
  <hr/>
  <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>4. Transportation Details</Typography>
  <Grid container >
    <Grid size={6}>
      <Typography variant="body2" className='waybill'><strong>Transporter ID :</strong> {E_invoice.transport.trans_id}</Typography>
      <Typography variant="body2" className='waybill'><strong>Name :</strong> {E_invoice.transport.trans_name}</Typography>
    </Grid>
    <Grid size={6}>
    <Typography variant="body2" className='waybill'><strong>Doc No :</strong> {E_invoice.transport.trans_doc_no}</Typography>
    <Typography variant="body2" className='waybill'><strong> Date :</strong> {moment(E_invoice.invoice[0]?.AckDt).format('DD/MM/YYYY')}</Typography>
    </Grid>
    
  </Grid>
  <hr />
  <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>5. Vehicle Details</Typography>
  <Grid container >
    <Grid size={4}>
      <Typography variant="body2" className='waybill'><strong>Vehicle No.:</strong> {E_invoice?.transport?.veh_no || "N/A"}</Typography>
    </Grid>
    <Grid size={4}>
    <Typography variant="body2" className='waybill'><strong>From:</strong> {E_invoice?.transport?.origin || ""}</Typography>
    </Grid>
    <Grid size={4}>
      <Typography variant="body2" className='waybill'><strong>CEWB No.:</strong> {}</Typography>
    </Grid>
  </Grid>

  {/* Declaration and Signature */}
  <hr />
  <Grid container>
    <Grid size={6}>
      <Typography variant="body2" className='waybill' style={{ fontStyle: "italic" }}>
        Declaration: We declare that this invoice shows the actual price of the goods and that all particulars are true and correct.
      </Typography>
    </Grid>
    <Grid style={{ textAlign: "right" }} size={6}>
      <Typography variant="body2" className='waybill' style={{ fontWeight: "bold" }}>Authorized Signatory</Typography>
    </Grid>
  </Grid>
      </div>
      </div>
    </>
  );
};

export default EWayBill;
