export const App_title = 'POS';

export const Create_label = 'Created Successfully';
export const reconciliatedLabel = 'Reconciliated Successfully';
export const Loan_Label = 'Requested for Loan';
export const Claim_Label = 'Requested for Claim';
export const Approve_lable = 'Approved Successfully';
export const Reject_lable = 'Rejected Successfully';
export const Update_label = 'Updated Successfully';
export const Manual_CheckIn = 'Checked In Successfully';
export const Manual_CheckOut = 'Checked Out Successfully';
export const Manual_breakStart = 'Break Started Successfully';
export const Manual_breakEnd = 'Break Ended Successfully';
export const Manual_correction = 'Manual Correction Done Successfully';
export const Delete_label = 'Deleted Successfully';
export const Leave_permission = 'Request Made Successfully';
export const No_Leave_Type = 'No Leave Policy Found!';
export const Cancel_label = 'Canceled Successfully';
export const Exist_label = 'Already Exist';
export const Exist_paymentName_label = 'Payment Name Already Exist';
export const LotExistAlert_label = 'Lot Number ALready Exist '
export const Error_label = 'Sorry something went wrong';
export const Try_again = 'Please try again later';
export const mail_send = 'Mail Sent Successfully';
export const Config_mail_send = 'Configure the mail and try again';
export const cannot_delete_label = 'Cannot Delete';
export const stockReconcilate_label = 'Matched';
export const invalidFile = 'Invalid File';
export const Test_label = 'Tested Successfully'
export const mail_not_sent = 'Mail Not Sent';
export const Not_available = 'Some Product Not Available';
export const Po_EXIST = 'Po Sequence Already Exist';
export const Verify_otp = 'OTP Verified Successfully!';
export const Invalid_otp = 'Invalid OTP!'
export const Otp_sent = 'OTP Sent Successfully!';
export const email_exceed = 'Email Exceeded! Try again later'
export const password_update = 'Password Updated Successfully!';
export const frontDesk_create = 'Front Desk User Created Successfully!';
export const frontDesk_update = 'Front Desk User Updated Successfully!';
export const userName_exists = 'User Name Already Exists!'
export const createSprintAlert = 'Sprint Created Successfully!';
export const updateSprintAlert = 'Sprint Started Successfully!';
export const completeSprintAlert = 'Sprint Completed Successfully!';
export const deleteSprintAlert = 'Sprint Deleted Successfully!';
export const invalidFileFormat = 'Incorrect File Format! Upload only images'
export const incentiveCreate = 'Incentive Created Successfully!'
export const incentiveDelete = 'Incentive Deleted Successfully!'
export const incentiveUpdate = 'Incentive Updated Successfully!'
export const lotNumber_exists = 'Lot Number Already Exists'
export const invalid_prefix = 'Check Prefix of the Username!'
export const invalid_employeeId = 'Duplicate Employee Code Found!'
export const employeeId_exists = 'Employee Code already exists!'
export const requiredFieldsAlertMessage = 'Please fill the required fields'
export const matchedTransactions= 'All Matched Transactions Created Successfully'
export const sales_product_create= 'All Products Created Successfully.For Created Products Purchase and then upload'
export const linkEstablishedMessage = 'Link Established Successfully'
export const unlinkMessage = 'Unlink Successfully'
export const receiptSentForApproval = 'Receipt Sent For Approval'
export const ReplacementMessage = 'Replacement Done Successfully'
export const notificationCleared = 'All notifications cleared Successfully'
export const category_exists = 'Please Check the entered category!'
export const designation_exists = 'Please Check the entered designation!'
export const location_exists = 'Please Check the entered location!'
export const departmentName_exists = 'Please Check the entered department!'
export const userRoleName_exists = 'Please Check the entered user role!'
export const tax_category_check = 'Please Check the tax category!'
export const set_up_mail='Setup Mail Configuration'
export const ledger_used = `Ledger Already Used! Can't able to delete ledger.`
export const searchErrorMessage = `Please enter at least 3 letters to begin searching!`
export const outstandingReport = 'Report sent successfully through whatsapp.'