export const RECHARGE_LOADING = 'RECHARGE_LOADING';
export const RECHARGE_ERROR = 'RECHARGE_ERROR';

export const RECHARGE_OPERATORS_LIST = 'RECHARGE_OPERATORS_LIST';
export const RECHARGE_OPERATOR_UPSERTED = 'RECHARGE_OPERATOR_UPSERTED';

export const RECHARGE_DASHBOARD = 'RECHARGE_DASHBOARD';

export const RECHARGE_WALLET_LOADS_LIST = 'RECHARGE_WALLET_LOADS_LIST';
export const RECHARGE_WALLET_LOAD_CREATED = 'RECHARGE_WALLET_LOAD_CREATED';

export const RECHARGE_TRANSACTIONS_LIST = 'RECHARGE_TRANSACTIONS_LIST';
export const RECHARGE_TRANSACTION_CREATED = 'RECHARGE_TRANSACTION_CREATED';

export const RECHARGE_PAYMENT_METHODS = 'RECHARGE_PAYMENT_METHODS';
export const RECHARGE_DAILY_SUMMARY = 'RECHARGE_DAILY_SUMMARY';
